security:
  oauth2:
    client:
      clientId: e24f768d9a5346509dd81d3f6811bd66
      clientSecret: bb5e0f916dcc4ccb953833c2cdc7f2b3
      preEstablishedRedirectUri: http://localhost:8080
      accessTokenUri: https://accounts.spotify.com/api/token
      userAuthorizationUri: https://accounts.spotify.com/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://accounts.spotify.com/me